import { useEffect, useRef } from "react";
import { printElement } from "../../Helper/Printer";
import { formatDate } from "../../Helper/utils";

const WarrantyPrinterModal = ({ open, setOpen, data }) => {
  const printRef = useRef();


  useEffect(() => {
    (async () => {
      if (open) {
        document.body.classList.add("overflow-hidden");
      } else {
        document.body.classList.remove("overflow-hidden");
      }
    })();
    return () => {
      document.body.classList.remove("overflow-hidden");
    };
  }, [open]);

  const handlePrint = () => {
    printElement(printRef);
  };

  if (!open) return null;
  return (
    <div
      onClick={() => {
        setOpen(false);
      }}
      className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center overflow-y-auto pt-10 px-3"
    >
      <div
        onClick={(e) => e.stopPropagation()}
        className="bg-white text-black dark:text-white dark:bg-[#1E2939] p-6 rounded-lg w-full sm:w-[90%] max-w-2xl max-h-[90vh] min-h-[70vh] overflow-y-auto shadow-lg"
      >
        <div ref={printRef} className="space-y-6">
          {/* Header */}
          <div className="text-center border-b pb-4">
            <h1 className="text-2xl font-bold tracking-wide">
              Warranty Invoice
            </h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Warranty ID: {data?._id}
            </p>
          </div>

          {/* Customer Info */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="bg-gray-100 dark:bg-[#0f172a] p-4 rounded">
              <h3 className="font-semibold mb-2">Customer</h3>
              <p>
                <b>Name:</b> {data?.SalesContactName}
              </p>
              <p>
                <b>Mobile:</b> {data?.SaleMobile}
              </p>
            </div>

            {/* Dates */}
            <div className="bg-gray-100 dark:bg-[#0f172a] p-4 rounded grid grid-cols-1 sm:grid-cols-2 gap-4">
              <p className="flex flex-col">
                <b>Sales Date:</b> {formatDate(data?.SalesDate)}
              </p>

              <p className="flex flex-col">
                <b>Warranty Date:</b> {formatDate(data?.DeliveryDate)}
              </p>
              <div className="bg-gray-100 dark:bg-[#0f172a] rounded">
                <p className="text-lg font-bold">Sale Warranty</p>
                <p className="text-sm font-semibold">
                  {data?.SaleWarranty} Days
                </p>
              </div>
            </div>
          </div>

          {/* Product Info */}
          <div className="bg-gray-100 dark:bg-[#0f172a] p-4 rounded space-y-2">
            <h3 className="font-semibold">Product Information</h3>
            <p>
              <b>Product:</b> {data?.Product}
            </p>
            {data?.NewProduct &&  <p>
              <b>New Product:</b> {data?.NewProduct}
            </p>}
          
            <p>
              <b>Serial:</b> {data?.serialNo}
            </p>
            {data?.NewserialNo && <p>
              <b>New Serial:</b> {data?.NewserialNo}
            </p>}
          </div>

          {/* Warranty Info */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"></div>

          {/* Footer */}
          <div className="border-t pt-4 text-center text-sm text-gray-500 dark:text-gray-400">
            This system is generated by - Bseba.com
          </div>
        </div>
        <div className="flex justify-between items-center mb-4 gap-5">
          <button
            className="global_button_red w-1/2"
            onClick={() => setOpen(false)}
          >
            Close
          </button>
          <button className="global_button w-1/2" onClick={handlePrint}>
            print
          </button>
        </div>
      </div>
    </div>
  );
};

export default WarrantyPrinterModal;
